// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.randioo_chat_server.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CSMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use CSMessage.newBuilder() to construct.
    private CSMessage() {
      initFields();
    }
    private CSMessage(boolean noInit) {}
    
    private static final CSMessage defaultInstance;
    public static CSMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.randioo_chat_server.protocol.ClientMessage.internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.randioo_chat_server.protocol.ClientMessage.internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginCheckAccountRequest loginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginCreateRoleRequest loginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.PingRequest pingRequest = 4;
    public static final int PINGREQUEST_FIELD_NUMBER = 4;
    private boolean hasPingRequest;
    private com.randioo.randioo_chat_server.protocol.Ping.PingRequest pingRequest_;
    public boolean hasPingRequest() { return hasPingRequest; }
    public com.randioo.randioo_chat_server.protocol.Ping.PingRequest getPingRequest() { return pingRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatEnterChatRoomRequest chatEnterChatRoomRequest = 5;
    public static final int CHATENTERCHATROOMREQUEST_FIELD_NUMBER = 5;
    private boolean hasChatEnterChatRoomRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest chatEnterChatRoomRequest_;
    public boolean hasChatEnterChatRoomRequest() { return hasChatEnterChatRoomRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest getChatEnterChatRoomRequest() { return chatEnterChatRoomRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatSendChatRequest chatSendChatRequest = 6;
    public static final int CHATSENDCHATREQUEST_FIELD_NUMBER = 6;
    private boolean hasChatSendChatRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest chatSendChatRequest_;
    public boolean hasChatSendChatRequest() { return hasChatSendChatRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest getChatSendChatRequest() { return chatSendChatRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatExitChatRoomRequest chatExitChatRoomRequest = 7;
    public static final int CHATEXITCHATROOMREQUEST_FIELD_NUMBER = 7;
    private boolean hasChatExitChatRoomRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest chatExitChatRoomRequest_;
    public boolean hasChatExitChatRoomRequest() { return hasChatExitChatRoomRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest getChatExitChatRoomRequest() { return chatExitChatRoomRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatSendPrivateChatRequest chatSendPrivateChatRequest = 8;
    public static final int CHATSENDPRIVATECHATREQUEST_FIELD_NUMBER = 8;
    private boolean hasChatSendPrivateChatRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest chatSendPrivateChatRequest_;
    public boolean hasChatSendPrivateChatRequest() { return hasChatSendPrivateChatRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest getChatSendPrivateChatRequest() { return chatSendPrivateChatRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatShowAccountChatRequest chatShowAccountChatRequest = 9;
    public static final int CHATSHOWACCOUNTCHATREQUEST_FIELD_NUMBER = 9;
    private boolean hasChatShowAccountChatRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest chatShowAccountChatRequest_;
    public boolean hasChatShowAccountChatRequest() { return hasChatShowAccountChatRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest getChatShowAccountChatRequest() { return chatShowAccountChatRequest_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatShowSummaryRequest chatShowSummaryRequest = 10;
    public static final int CHATSHOWSUMMARYREQUEST_FIELD_NUMBER = 10;
    private boolean hasChatShowSummaryRequest;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest chatShowSummaryRequest_;
    public boolean hasChatShowSummaryRequest() { return hasChatShowSummaryRequest; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest getChatShowSummaryRequest() { return chatShowSummaryRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      pingRequest_ = com.randioo.randioo_chat_server.protocol.Ping.PingRequest.getDefaultInstance();
      chatEnterChatRoomRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.getDefaultInstance();
      chatSendChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.getDefaultInstance();
      chatExitChatRoomRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.getDefaultInstance();
      chatSendPrivateChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.getDefaultInstance();
      chatShowAccountChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.getDefaultInstance();
      chatShowSummaryRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasPingRequest()) {
        output.writeMessage(4, getPingRequest());
      }
      if (hasChatEnterChatRoomRequest()) {
        output.writeMessage(5, getChatEnterChatRoomRequest());
      }
      if (hasChatSendChatRequest()) {
        output.writeMessage(6, getChatSendChatRequest());
      }
      if (hasChatExitChatRoomRequest()) {
        output.writeMessage(7, getChatExitChatRoomRequest());
      }
      if (hasChatSendPrivateChatRequest()) {
        output.writeMessage(8, getChatSendPrivateChatRequest());
      }
      if (hasChatShowAccountChatRequest()) {
        output.writeMessage(9, getChatShowAccountChatRequest());
      }
      if (hasChatShowSummaryRequest()) {
        output.writeMessage(10, getChatShowSummaryRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasPingRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPingRequest());
      }
      if (hasChatEnterChatRoomRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getChatEnterChatRoomRequest());
      }
      if (hasChatSendChatRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getChatSendChatRequest());
      }
      if (hasChatExitChatRoomRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getChatExitChatRoomRequest());
      }
      if (hasChatSendPrivateChatRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getChatSendPrivateChatRequest());
      }
      if (hasChatShowAccountChatRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getChatShowAccountChatRequest());
      }
      if (hasChatShowSummaryRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getChatShowSummaryRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage result;
      
      // Construct using com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage();
        return builder;
      }
      
      protected com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.getDescriptor();
      }
      
      public com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage getDefaultInstanceForType() {
        return com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage) {
          return mergeFrom((com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage other) {
        if (other == com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasPingRequest()) {
          mergePingRequest(other.getPingRequest());
        }
        if (other.hasChatEnterChatRoomRequest()) {
          mergeChatEnterChatRoomRequest(other.getChatEnterChatRoomRequest());
        }
        if (other.hasChatSendChatRequest()) {
          mergeChatSendChatRequest(other.getChatSendChatRequest());
        }
        if (other.hasChatExitChatRoomRequest()) {
          mergeChatExitChatRoomRequest(other.getChatExitChatRoomRequest());
        }
        if (other.hasChatSendPrivateChatRequest()) {
          mergeChatSendPrivateChatRequest(other.getChatSendPrivateChatRequest());
        }
        if (other.hasChatShowAccountChatRequest()) {
          mergeChatShowAccountChatRequest(other.getChatShowAccountChatRequest());
        }
        if (other.hasChatShowSummaryRequest()) {
          mergeChatShowSummaryRequest(other.getChatShowSummaryRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.randioo_chat_server.protocol.Ping.PingRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Ping.PingRequest.newBuilder();
              if (hasPingRequest()) {
                subBuilder.mergeFrom(getPingRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPingRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.newBuilder();
              if (hasChatEnterChatRoomRequest()) {
                subBuilder.mergeFrom(getChatEnterChatRoomRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatEnterChatRoomRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.newBuilder();
              if (hasChatSendChatRequest()) {
                subBuilder.mergeFrom(getChatSendChatRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatSendChatRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.newBuilder();
              if (hasChatExitChatRoomRequest()) {
                subBuilder.mergeFrom(getChatExitChatRoomRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatExitChatRoomRequest(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.newBuilder();
              if (hasChatSendPrivateChatRequest()) {
                subBuilder.mergeFrom(getChatSendPrivateChatRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatSendPrivateChatRequest(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.newBuilder();
              if (hasChatShowAccountChatRequest()) {
                subBuilder.mergeFrom(getChatShowAccountChatRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatShowAccountChatRequest(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.newBuilder();
              if (hasChatShowSummaryRequest()) {
                subBuilder.mergeFrom(getChatShowSummaryRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatShowSummaryRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginCheckAccountRequest loginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginCreateRoleRequest loginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginGetRoleDataRequest loginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.PingRequest pingRequest = 4;
      public boolean hasPingRequest() {
        return result.hasPingRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Ping.PingRequest getPingRequest() {
        return result.getPingRequest();
      }
      public Builder setPingRequest(com.randioo.randioo_chat_server.protocol.Ping.PingRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPingRequest = true;
        result.pingRequest_ = value;
        return this;
      }
      public Builder setPingRequest(com.randioo.randioo_chat_server.protocol.Ping.PingRequest.Builder builderForValue) {
        result.hasPingRequest = true;
        result.pingRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergePingRequest(com.randioo.randioo_chat_server.protocol.Ping.PingRequest value) {
        if (result.hasPingRequest() &&
            result.pingRequest_ != com.randioo.randioo_chat_server.protocol.Ping.PingRequest.getDefaultInstance()) {
          result.pingRequest_ =
            com.randioo.randioo_chat_server.protocol.Ping.PingRequest.newBuilder(result.pingRequest_).mergeFrom(value).buildPartial();
        } else {
          result.pingRequest_ = value;
        }
        result.hasPingRequest = true;
        return this;
      }
      public Builder clearPingRequest() {
        result.hasPingRequest = false;
        result.pingRequest_ = com.randioo.randioo_chat_server.protocol.Ping.PingRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatEnterChatRoomRequest chatEnterChatRoomRequest = 5;
      public boolean hasChatEnterChatRoomRequest() {
        return result.hasChatEnterChatRoomRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest getChatEnterChatRoomRequest() {
        return result.getChatEnterChatRoomRequest();
      }
      public Builder setChatEnterChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatEnterChatRoomRequest = true;
        result.chatEnterChatRoomRequest_ = value;
        return this;
      }
      public Builder setChatEnterChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.Builder builderForValue) {
        result.hasChatEnterChatRoomRequest = true;
        result.chatEnterChatRoomRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatEnterChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest value) {
        if (result.hasChatEnterChatRoomRequest() &&
            result.chatEnterChatRoomRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.getDefaultInstance()) {
          result.chatEnterChatRoomRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.newBuilder(result.chatEnterChatRoomRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatEnterChatRoomRequest_ = value;
        }
        result.hasChatEnterChatRoomRequest = true;
        return this;
      }
      public Builder clearChatEnterChatRoomRequest() {
        result.hasChatEnterChatRoomRequest = false;
        result.chatEnterChatRoomRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatSendChatRequest chatSendChatRequest = 6;
      public boolean hasChatSendChatRequest() {
        return result.hasChatSendChatRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest getChatSendChatRequest() {
        return result.getChatSendChatRequest();
      }
      public Builder setChatSendChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatSendChatRequest = true;
        result.chatSendChatRequest_ = value;
        return this;
      }
      public Builder setChatSendChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.Builder builderForValue) {
        result.hasChatSendChatRequest = true;
        result.chatSendChatRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatSendChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest value) {
        if (result.hasChatSendChatRequest() &&
            result.chatSendChatRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.getDefaultInstance()) {
          result.chatSendChatRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.newBuilder(result.chatSendChatRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatSendChatRequest_ = value;
        }
        result.hasChatSendChatRequest = true;
        return this;
      }
      public Builder clearChatSendChatRequest() {
        result.hasChatSendChatRequest = false;
        result.chatSendChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatExitChatRoomRequest chatExitChatRoomRequest = 7;
      public boolean hasChatExitChatRoomRequest() {
        return result.hasChatExitChatRoomRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest getChatExitChatRoomRequest() {
        return result.getChatExitChatRoomRequest();
      }
      public Builder setChatExitChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatExitChatRoomRequest = true;
        result.chatExitChatRoomRequest_ = value;
        return this;
      }
      public Builder setChatExitChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.Builder builderForValue) {
        result.hasChatExitChatRoomRequest = true;
        result.chatExitChatRoomRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatExitChatRoomRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest value) {
        if (result.hasChatExitChatRoomRequest() &&
            result.chatExitChatRoomRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.getDefaultInstance()) {
          result.chatExitChatRoomRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.newBuilder(result.chatExitChatRoomRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatExitChatRoomRequest_ = value;
        }
        result.hasChatExitChatRoomRequest = true;
        return this;
      }
      public Builder clearChatExitChatRoomRequest() {
        result.hasChatExitChatRoomRequest = false;
        result.chatExitChatRoomRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatSendPrivateChatRequest chatSendPrivateChatRequest = 8;
      public boolean hasChatSendPrivateChatRequest() {
        return result.hasChatSendPrivateChatRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest getChatSendPrivateChatRequest() {
        return result.getChatSendPrivateChatRequest();
      }
      public Builder setChatSendPrivateChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatSendPrivateChatRequest = true;
        result.chatSendPrivateChatRequest_ = value;
        return this;
      }
      public Builder setChatSendPrivateChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.Builder builderForValue) {
        result.hasChatSendPrivateChatRequest = true;
        result.chatSendPrivateChatRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatSendPrivateChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest value) {
        if (result.hasChatSendPrivateChatRequest() &&
            result.chatSendPrivateChatRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.getDefaultInstance()) {
          result.chatSendPrivateChatRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.newBuilder(result.chatSendPrivateChatRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatSendPrivateChatRequest_ = value;
        }
        result.hasChatSendPrivateChatRequest = true;
        return this;
      }
      public Builder clearChatSendPrivateChatRequest() {
        result.hasChatSendPrivateChatRequest = false;
        result.chatSendPrivateChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatShowAccountChatRequest chatShowAccountChatRequest = 9;
      public boolean hasChatShowAccountChatRequest() {
        return result.hasChatShowAccountChatRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest getChatShowAccountChatRequest() {
        return result.getChatShowAccountChatRequest();
      }
      public Builder setChatShowAccountChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatShowAccountChatRequest = true;
        result.chatShowAccountChatRequest_ = value;
        return this;
      }
      public Builder setChatShowAccountChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.Builder builderForValue) {
        result.hasChatShowAccountChatRequest = true;
        result.chatShowAccountChatRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatShowAccountChatRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest value) {
        if (result.hasChatShowAccountChatRequest() &&
            result.chatShowAccountChatRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.getDefaultInstance()) {
          result.chatShowAccountChatRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.newBuilder(result.chatShowAccountChatRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatShowAccountChatRequest_ = value;
        }
        result.hasChatShowAccountChatRequest = true;
        return this;
      }
      public Builder clearChatShowAccountChatRequest() {
        result.hasChatShowAccountChatRequest = false;
        result.chatShowAccountChatRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatShowSummaryRequest chatShowSummaryRequest = 10;
      public boolean hasChatShowSummaryRequest() {
        return result.hasChatShowSummaryRequest();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest getChatShowSummaryRequest() {
        return result.getChatShowSummaryRequest();
      }
      public Builder setChatShowSummaryRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatShowSummaryRequest = true;
        result.chatShowSummaryRequest_ = value;
        return this;
      }
      public Builder setChatShowSummaryRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.Builder builderForValue) {
        result.hasChatShowSummaryRequest = true;
        result.chatShowSummaryRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatShowSummaryRequest(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest value) {
        if (result.hasChatShowSummaryRequest() &&
            result.chatShowSummaryRequest_ != com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.getDefaultInstance()) {
          result.chatShowSummaryRequest_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.newBuilder(result.chatShowSummaryRequest_).mergeFrom(value).buildPartial();
        } else {
          result.chatShowSummaryRequest_ = value;
        }
        result.hasChatShowSummaryRequest = true;
        return this;
      }
      public Builder clearChatShowSummaryRequest() {
        result.hasChatShowSummaryRequest = false;
        result.chatShowSummaryRequest_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.randioo_chat_server.protocol.CSMessage)
    }
    
    static {
      defaultInstance = new CSMessage(true);
      com.randioo.randioo_chat_server.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.randioo_chat_server.protocol.CSMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\022(com.randioo.randi" +
      "oo_chat_server.protocol\032\013Login.proto\032\nPi" +
      "ng.proto\032\nChat.proto\"\337\007\n\tCSMessage\022d\n\030lo" +
      "ginCheckAccountRequest\030\001 \001(\0132B.com.randi" +
      "oo.randioo_chat_server.protocol.LoginChe" +
      "ckAccountRequest\022`\n\026loginCreateRoleReque" +
      "st\030\002 \001(\0132@.com.randioo.randioo_chat_serv" +
      "er.protocol.LoginCreateRoleRequest\022b\n\027lo" +
      "ginGetRoleDataRequest\030\003 \001(\0132A.com.randio" +
      "o.randioo_chat_server.protocol.LoginGetR",
      "oleDataRequest\022J\n\013pingRequest\030\004 \001(\01325.co" +
      "m.randioo.randioo_chat_server.protocol.P" +
      "ingRequest\022d\n\030chatEnterChatRoomRequest\030\005" +
      " \001(\0132B.com.randioo.randioo_chat_server.p" +
      "rotocol.ChatEnterChatRoomRequest\022Z\n\023chat" +
      "SendChatRequest\030\006 \001(\0132=.com.randioo.rand" +
      "ioo_chat_server.protocol.ChatSendChatReq" +
      "uest\022b\n\027chatExitChatRoomRequest\030\007 \001(\0132A." +
      "com.randioo.randioo_chat_server.protocol" +
      ".ChatExitChatRoomRequest\022h\n\032chatSendPriv",
      "ateChatRequest\030\010 \001(\0132D.com.randioo.randi" +
      "oo_chat_server.protocol.ChatSendPrivateC" +
      "hatRequest\022h\n\032chatShowAccountChatRequest" +
      "\030\t \001(\0132D.com.randioo.randioo_chat_server" +
      ".protocol.ChatShowAccountChatRequest\022`\n\026" +
      "chatShowSummaryRequest\030\n \001(\0132@.com.randi" +
      "oo.randioo_chat_server.protocol.ChatShow" +
      "SummaryRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_randioo_chat_server_protocol_CSMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "PingRequest", "ChatEnterChatRoomRequest", "ChatSendChatRequest", "ChatExitChatRoomRequest", "ChatSendPrivateChatRequest", "ChatShowAccountChatRequest", "ChatShowSummaryRequest", },
              com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.class,
              com.randioo.randioo_chat_server.protocol.ClientMessage.CSMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.randioo_chat_server.protocol.Login.getDescriptor(),
          com.randioo.randioo_chat_server.protocol.Ping.getDescriptor(),
          com.randioo.randioo_chat_server.protocol.Chat.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
