// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package com.randioo.randioo_chat_server.protocol;

public final class ServerMessage {
  private ServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use SCMessage.newBuilder() to construct.
    private SCMessage() {
      initFields();
    }
    private SCMessage(boolean noInit) {}
    
    private static final SCMessage defaultInstance;
    public static SCMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.randioo_chat_server.protocol.ServerMessage.internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.randioo_chat_server.protocol.ServerMessage.internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginCheckAccountResponse loginCheckAccountResponse = 1;
    public static final int LOGINCHECKACCOUNTRESPONSE_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountResponse;
    private com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse loginCheckAccountResponse_;
    public boolean hasLoginCheckAccountResponse() { return hasLoginCheckAccountResponse; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() { return loginCheckAccountResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginCreateRoleResponse loginCreateRoleResponse = 2;
    public static final int LOGINCREATEROLERESPONSE_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleResponse;
    private com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse loginCreateRoleResponse_;
    public boolean hasLoginCreateRoleResponse() { return hasLoginCreateRoleResponse; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() { return loginCreateRoleResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.LoginGetRoleDataResponse loginGetRoleDataResponse = 3;
    public static final int LOGINGETROLEDATARESPONSE_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataResponse;
    private com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse loginGetRoleDataResponse_;
    public boolean hasLoginGetRoleDataResponse() { return hasLoginGetRoleDataResponse; }
    public com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() { return loginGetRoleDataResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.PingResponse pingResponse = 4;
    public static final int PINGRESPONSE_FIELD_NUMBER = 4;
    private boolean hasPingResponse;
    private com.randioo.randioo_chat_server.protocol.Ping.PingResponse pingResponse_;
    public boolean hasPingResponse() { return hasPingResponse; }
    public com.randioo.randioo_chat_server.protocol.Ping.PingResponse getPingResponse() { return pingResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatEnterChatRoomResponse chatEnterChatRoomResponse = 5;
    public static final int CHATENTERCHATROOMRESPONSE_FIELD_NUMBER = 5;
    private boolean hasChatEnterChatRoomResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse chatEnterChatRoomResponse_;
    public boolean hasChatEnterChatRoomResponse() { return hasChatEnterChatRoomResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse getChatEnterChatRoomResponse() { return chatEnterChatRoomResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatSendChatResponse chatSendChatResponse = 6;
    public static final int CHATSENDCHATRESPONSE_FIELD_NUMBER = 6;
    private boolean hasChatSendChatResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse chatSendChatResponse_;
    public boolean hasChatSendChatResponse() { return hasChatSendChatResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse getChatSendChatResponse() { return chatSendChatResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatExitChatRoomResponse chatExitChatRoomResponse = 7;
    public static final int CHATEXITCHATROOMRESPONSE_FIELD_NUMBER = 7;
    private boolean hasChatExitChatRoomResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse chatExitChatRoomResponse_;
    public boolean hasChatExitChatRoomResponse() { return hasChatExitChatRoomResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse getChatExitChatRoomResponse() { return chatExitChatRoomResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatSendPrivateChatResponse chatSendPrivateChatResponse = 8;
    public static final int CHATSENDPRIVATECHATRESPONSE_FIELD_NUMBER = 8;
    private boolean hasChatSendPrivateChatResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse chatSendPrivateChatResponse_;
    public boolean hasChatSendPrivateChatResponse() { return hasChatSendPrivateChatResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse getChatSendPrivateChatResponse() { return chatSendPrivateChatResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatShowAccountChatResponse chatShowAccountChatResponse = 9;
    public static final int CHATSHOWACCOUNTCHATRESPONSE_FIELD_NUMBER = 9;
    private boolean hasChatShowAccountChatResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse chatShowAccountChatResponse_;
    public boolean hasChatShowAccountChatResponse() { return hasChatShowAccountChatResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse getChatShowAccountChatResponse() { return chatShowAccountChatResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.ChatShowSummaryResponse chatShowSummaryResponse = 10;
    public static final int CHATSHOWSUMMARYRESPONSE_FIELD_NUMBER = 10;
    private boolean hasChatShowSummaryResponse;
    private com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse chatShowSummaryResponse_;
    public boolean hasChatShowSummaryResponse() { return hasChatShowSummaryResponse; }
    public com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse getChatShowSummaryResponse() { return chatShowSummaryResponse_; }
    
    // optional .com.randioo.randioo_chat_server.protocol.SCChatReceiveChat scChatReceiveChat = 11;
    public static final int SCCHATRECEIVECHAT_FIELD_NUMBER = 11;
    private boolean hasScChatReceiveChat;
    private com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat scChatReceiveChat_;
    public boolean hasScChatReceiveChat() { return hasScChatReceiveChat; }
    public com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat getScChatReceiveChat() { return scChatReceiveChat_; }
    
    private void initFields() {
      loginCheckAccountResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance();
      loginCreateRoleResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance();
      loginGetRoleDataResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
      pingResponse_ = com.randioo.randioo_chat_server.protocol.Ping.PingResponse.getDefaultInstance();
      chatEnterChatRoomResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.getDefaultInstance();
      chatSendChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.getDefaultInstance();
      chatExitChatRoomResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.getDefaultInstance();
      chatSendPrivateChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.getDefaultInstance();
      chatShowAccountChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.getDefaultInstance();
      chatShowSummaryResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.getDefaultInstance();
      scChatReceiveChat_ = com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountResponse()) {
        output.writeMessage(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        output.writeMessage(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        output.writeMessage(3, getLoginGetRoleDataResponse());
      }
      if (hasPingResponse()) {
        output.writeMessage(4, getPingResponse());
      }
      if (hasChatEnterChatRoomResponse()) {
        output.writeMessage(5, getChatEnterChatRoomResponse());
      }
      if (hasChatSendChatResponse()) {
        output.writeMessage(6, getChatSendChatResponse());
      }
      if (hasChatExitChatRoomResponse()) {
        output.writeMessage(7, getChatExitChatRoomResponse());
      }
      if (hasChatSendPrivateChatResponse()) {
        output.writeMessage(8, getChatSendPrivateChatResponse());
      }
      if (hasChatShowAccountChatResponse()) {
        output.writeMessage(9, getChatShowAccountChatResponse());
      }
      if (hasChatShowSummaryResponse()) {
        output.writeMessage(10, getChatShowSummaryResponse());
      }
      if (hasScChatReceiveChat()) {
        output.writeMessage(11, getScChatReceiveChat());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataResponse());
      }
      if (hasPingResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getPingResponse());
      }
      if (hasChatEnterChatRoomResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getChatEnterChatRoomResponse());
      }
      if (hasChatSendChatResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getChatSendChatResponse());
      }
      if (hasChatExitChatRoomResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getChatExitChatRoomResponse());
      }
      if (hasChatSendPrivateChatResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getChatSendPrivateChatResponse());
      }
      if (hasChatShowAccountChatResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getChatShowAccountChatResponse());
      }
      if (hasChatShowSummaryResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getChatShowSummaryResponse());
      }
      if (hasScChatReceiveChat()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getScChatReceiveChat());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage result;
      
      // Construct using com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage();
        return builder;
      }
      
      protected com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.getDescriptor();
      }
      
      public com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage getDefaultInstanceForType() {
        return com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage) {
          return mergeFrom((com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage other) {
        if (other == com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountResponse()) {
          mergeLoginCheckAccountResponse(other.getLoginCheckAccountResponse());
        }
        if (other.hasLoginCreateRoleResponse()) {
          mergeLoginCreateRoleResponse(other.getLoginCreateRoleResponse());
        }
        if (other.hasLoginGetRoleDataResponse()) {
          mergeLoginGetRoleDataResponse(other.getLoginGetRoleDataResponse());
        }
        if (other.hasPingResponse()) {
          mergePingResponse(other.getPingResponse());
        }
        if (other.hasChatEnterChatRoomResponse()) {
          mergeChatEnterChatRoomResponse(other.getChatEnterChatRoomResponse());
        }
        if (other.hasChatSendChatResponse()) {
          mergeChatSendChatResponse(other.getChatSendChatResponse());
        }
        if (other.hasChatExitChatRoomResponse()) {
          mergeChatExitChatRoomResponse(other.getChatExitChatRoomResponse());
        }
        if (other.hasChatSendPrivateChatResponse()) {
          mergeChatSendPrivateChatResponse(other.getChatSendPrivateChatResponse());
        }
        if (other.hasChatShowAccountChatResponse()) {
          mergeChatShowAccountChatResponse(other.getChatShowAccountChatResponse());
        }
        if (other.hasChatShowSummaryResponse()) {
          mergeChatShowSummaryResponse(other.getChatShowSummaryResponse());
        }
        if (other.hasScChatReceiveChat()) {
          mergeScChatReceiveChat(other.getScChatReceiveChat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.newBuilder();
              if (hasLoginCheckAccountResponse()) {
                subBuilder.mergeFrom(getLoginCheckAccountResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountResponse(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.newBuilder();
              if (hasLoginCreateRoleResponse()) {
                subBuilder.mergeFrom(getLoginCreateRoleResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleResponse(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.newBuilder();
              if (hasLoginGetRoleDataResponse()) {
                subBuilder.mergeFrom(getLoginGetRoleDataResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataResponse(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.randioo_chat_server.protocol.Ping.PingResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Ping.PingResponse.newBuilder();
              if (hasPingResponse()) {
                subBuilder.mergeFrom(getPingResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPingResponse(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.newBuilder();
              if (hasChatEnterChatRoomResponse()) {
                subBuilder.mergeFrom(getChatEnterChatRoomResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatEnterChatRoomResponse(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.newBuilder();
              if (hasChatSendChatResponse()) {
                subBuilder.mergeFrom(getChatSendChatResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatSendChatResponse(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.newBuilder();
              if (hasChatExitChatRoomResponse()) {
                subBuilder.mergeFrom(getChatExitChatRoomResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatExitChatRoomResponse(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.newBuilder();
              if (hasChatSendPrivateChatResponse()) {
                subBuilder.mergeFrom(getChatSendPrivateChatResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatSendPrivateChatResponse(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.newBuilder();
              if (hasChatShowAccountChatResponse()) {
                subBuilder.mergeFrom(getChatShowAccountChatResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatShowAccountChatResponse(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.newBuilder();
              if (hasChatShowSummaryResponse()) {
                subBuilder.mergeFrom(getChatShowSummaryResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChatShowSummaryResponse(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.Builder subBuilder = com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.newBuilder();
              if (hasScChatReceiveChat()) {
                subBuilder.mergeFrom(getScChatReceiveChat());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setScChatReceiveChat(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginCheckAccountResponse loginCheckAccountResponse = 1;
      public boolean hasLoginCheckAccountResponse() {
        return result.hasLoginCheckAccountResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() {
        return result.getLoginCheckAccountResponse();
      }
      public Builder setLoginCheckAccountResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = value;
        return this;
      }
      public Builder setLoginCheckAccountResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.Builder builderForValue) {
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse value) {
        if (result.hasLoginCheckAccountResponse() &&
            result.loginCheckAccountResponse_ != com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance()) {
          result.loginCheckAccountResponse_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.newBuilder(result.loginCheckAccountResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountResponse_ = value;
        }
        result.hasLoginCheckAccountResponse = true;
        return this;
      }
      public Builder clearLoginCheckAccountResponse() {
        result.hasLoginCheckAccountResponse = false;
        result.loginCheckAccountResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginCreateRoleResponse loginCreateRoleResponse = 2;
      public boolean hasLoginCreateRoleResponse() {
        return result.hasLoginCreateRoleResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() {
        return result.getLoginCreateRoleResponse();
      }
      public Builder setLoginCreateRoleResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = value;
        return this;
      }
      public Builder setLoginCreateRoleResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.Builder builderForValue) {
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleResponse(com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse value) {
        if (result.hasLoginCreateRoleResponse() &&
            result.loginCreateRoleResponse_ != com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance()) {
          result.loginCreateRoleResponse_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.newBuilder(result.loginCreateRoleResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleResponse_ = value;
        }
        result.hasLoginCreateRoleResponse = true;
        return this;
      }
      public Builder clearLoginCreateRoleResponse() {
        result.hasLoginCreateRoleResponse = false;
        result.loginCreateRoleResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.LoginGetRoleDataResponse loginGetRoleDataResponse = 3;
      public boolean hasLoginGetRoleDataResponse() {
        return result.hasLoginGetRoleDataResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() {
        return result.getLoginGetRoleDataResponse();
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.Builder builderForValue) {
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataResponse(com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse value) {
        if (result.hasLoginGetRoleDataResponse() &&
            result.loginGetRoleDataResponse_ != com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance()) {
          result.loginGetRoleDataResponse_ =
            com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.newBuilder(result.loginGetRoleDataResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataResponse_ = value;
        }
        result.hasLoginGetRoleDataResponse = true;
        return this;
      }
      public Builder clearLoginGetRoleDataResponse() {
        result.hasLoginGetRoleDataResponse = false;
        result.loginGetRoleDataResponse_ = com.randioo.randioo_chat_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.PingResponse pingResponse = 4;
      public boolean hasPingResponse() {
        return result.hasPingResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Ping.PingResponse getPingResponse() {
        return result.getPingResponse();
      }
      public Builder setPingResponse(com.randioo.randioo_chat_server.protocol.Ping.PingResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasPingResponse = true;
        result.pingResponse_ = value;
        return this;
      }
      public Builder setPingResponse(com.randioo.randioo_chat_server.protocol.Ping.PingResponse.Builder builderForValue) {
        result.hasPingResponse = true;
        result.pingResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergePingResponse(com.randioo.randioo_chat_server.protocol.Ping.PingResponse value) {
        if (result.hasPingResponse() &&
            result.pingResponse_ != com.randioo.randioo_chat_server.protocol.Ping.PingResponse.getDefaultInstance()) {
          result.pingResponse_ =
            com.randioo.randioo_chat_server.protocol.Ping.PingResponse.newBuilder(result.pingResponse_).mergeFrom(value).buildPartial();
        } else {
          result.pingResponse_ = value;
        }
        result.hasPingResponse = true;
        return this;
      }
      public Builder clearPingResponse() {
        result.hasPingResponse = false;
        result.pingResponse_ = com.randioo.randioo_chat_server.protocol.Ping.PingResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatEnterChatRoomResponse chatEnterChatRoomResponse = 5;
      public boolean hasChatEnterChatRoomResponse() {
        return result.hasChatEnterChatRoomResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse getChatEnterChatRoomResponse() {
        return result.getChatEnterChatRoomResponse();
      }
      public Builder setChatEnterChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatEnterChatRoomResponse = true;
        result.chatEnterChatRoomResponse_ = value;
        return this;
      }
      public Builder setChatEnterChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.Builder builderForValue) {
        result.hasChatEnterChatRoomResponse = true;
        result.chatEnterChatRoomResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatEnterChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse value) {
        if (result.hasChatEnterChatRoomResponse() &&
            result.chatEnterChatRoomResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.getDefaultInstance()) {
          result.chatEnterChatRoomResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.newBuilder(result.chatEnterChatRoomResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatEnterChatRoomResponse_ = value;
        }
        result.hasChatEnterChatRoomResponse = true;
        return this;
      }
      public Builder clearChatEnterChatRoomResponse() {
        result.hasChatEnterChatRoomResponse = false;
        result.chatEnterChatRoomResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatEnterChatRoomResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatSendChatResponse chatSendChatResponse = 6;
      public boolean hasChatSendChatResponse() {
        return result.hasChatSendChatResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse getChatSendChatResponse() {
        return result.getChatSendChatResponse();
      }
      public Builder setChatSendChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatSendChatResponse = true;
        result.chatSendChatResponse_ = value;
        return this;
      }
      public Builder setChatSendChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.Builder builderForValue) {
        result.hasChatSendChatResponse = true;
        result.chatSendChatResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatSendChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse value) {
        if (result.hasChatSendChatResponse() &&
            result.chatSendChatResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.getDefaultInstance()) {
          result.chatSendChatResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.newBuilder(result.chatSendChatResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatSendChatResponse_ = value;
        }
        result.hasChatSendChatResponse = true;
        return this;
      }
      public Builder clearChatSendChatResponse() {
        result.hasChatSendChatResponse = false;
        result.chatSendChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendChatResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatExitChatRoomResponse chatExitChatRoomResponse = 7;
      public boolean hasChatExitChatRoomResponse() {
        return result.hasChatExitChatRoomResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse getChatExitChatRoomResponse() {
        return result.getChatExitChatRoomResponse();
      }
      public Builder setChatExitChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatExitChatRoomResponse = true;
        result.chatExitChatRoomResponse_ = value;
        return this;
      }
      public Builder setChatExitChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.Builder builderForValue) {
        result.hasChatExitChatRoomResponse = true;
        result.chatExitChatRoomResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatExitChatRoomResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse value) {
        if (result.hasChatExitChatRoomResponse() &&
            result.chatExitChatRoomResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.getDefaultInstance()) {
          result.chatExitChatRoomResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.newBuilder(result.chatExitChatRoomResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatExitChatRoomResponse_ = value;
        }
        result.hasChatExitChatRoomResponse = true;
        return this;
      }
      public Builder clearChatExitChatRoomResponse() {
        result.hasChatExitChatRoomResponse = false;
        result.chatExitChatRoomResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatExitChatRoomResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatSendPrivateChatResponse chatSendPrivateChatResponse = 8;
      public boolean hasChatSendPrivateChatResponse() {
        return result.hasChatSendPrivateChatResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse getChatSendPrivateChatResponse() {
        return result.getChatSendPrivateChatResponse();
      }
      public Builder setChatSendPrivateChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatSendPrivateChatResponse = true;
        result.chatSendPrivateChatResponse_ = value;
        return this;
      }
      public Builder setChatSendPrivateChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.Builder builderForValue) {
        result.hasChatSendPrivateChatResponse = true;
        result.chatSendPrivateChatResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatSendPrivateChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse value) {
        if (result.hasChatSendPrivateChatResponse() &&
            result.chatSendPrivateChatResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.getDefaultInstance()) {
          result.chatSendPrivateChatResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.newBuilder(result.chatSendPrivateChatResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatSendPrivateChatResponse_ = value;
        }
        result.hasChatSendPrivateChatResponse = true;
        return this;
      }
      public Builder clearChatSendPrivateChatResponse() {
        result.hasChatSendPrivateChatResponse = false;
        result.chatSendPrivateChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatSendPrivateChatResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatShowAccountChatResponse chatShowAccountChatResponse = 9;
      public boolean hasChatShowAccountChatResponse() {
        return result.hasChatShowAccountChatResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse getChatShowAccountChatResponse() {
        return result.getChatShowAccountChatResponse();
      }
      public Builder setChatShowAccountChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatShowAccountChatResponse = true;
        result.chatShowAccountChatResponse_ = value;
        return this;
      }
      public Builder setChatShowAccountChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.Builder builderForValue) {
        result.hasChatShowAccountChatResponse = true;
        result.chatShowAccountChatResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatShowAccountChatResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse value) {
        if (result.hasChatShowAccountChatResponse() &&
            result.chatShowAccountChatResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.getDefaultInstance()) {
          result.chatShowAccountChatResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.newBuilder(result.chatShowAccountChatResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatShowAccountChatResponse_ = value;
        }
        result.hasChatShowAccountChatResponse = true;
        return this;
      }
      public Builder clearChatShowAccountChatResponse() {
        result.hasChatShowAccountChatResponse = false;
        result.chatShowAccountChatResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowAccountChatResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.ChatShowSummaryResponse chatShowSummaryResponse = 10;
      public boolean hasChatShowSummaryResponse() {
        return result.hasChatShowSummaryResponse();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse getChatShowSummaryResponse() {
        return result.getChatShowSummaryResponse();
      }
      public Builder setChatShowSummaryResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasChatShowSummaryResponse = true;
        result.chatShowSummaryResponse_ = value;
        return this;
      }
      public Builder setChatShowSummaryResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.Builder builderForValue) {
        result.hasChatShowSummaryResponse = true;
        result.chatShowSummaryResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeChatShowSummaryResponse(com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse value) {
        if (result.hasChatShowSummaryResponse() &&
            result.chatShowSummaryResponse_ != com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.getDefaultInstance()) {
          result.chatShowSummaryResponse_ =
            com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.newBuilder(result.chatShowSummaryResponse_).mergeFrom(value).buildPartial();
        } else {
          result.chatShowSummaryResponse_ = value;
        }
        result.hasChatShowSummaryResponse = true;
        return this;
      }
      public Builder clearChatShowSummaryResponse() {
        result.hasChatShowSummaryResponse = false;
        result.chatShowSummaryResponse_ = com.randioo.randioo_chat_server.protocol.Chat.ChatShowSummaryResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.randioo_chat_server.protocol.SCChatReceiveChat scChatReceiveChat = 11;
      public boolean hasScChatReceiveChat() {
        return result.hasScChatReceiveChat();
      }
      public com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat getScChatReceiveChat() {
        return result.getScChatReceiveChat();
      }
      public Builder setScChatReceiveChat(com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasScChatReceiveChat = true;
        result.scChatReceiveChat_ = value;
        return this;
      }
      public Builder setScChatReceiveChat(com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.Builder builderForValue) {
        result.hasScChatReceiveChat = true;
        result.scChatReceiveChat_ = builderForValue.build();
        return this;
      }
      public Builder mergeScChatReceiveChat(com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat value) {
        if (result.hasScChatReceiveChat() &&
            result.scChatReceiveChat_ != com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.getDefaultInstance()) {
          result.scChatReceiveChat_ =
            com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.newBuilder(result.scChatReceiveChat_).mergeFrom(value).buildPartial();
        } else {
          result.scChatReceiveChat_ = value;
        }
        result.hasScChatReceiveChat = true;
        return this;
      }
      public Builder clearScChatReceiveChat() {
        result.hasScChatReceiveChat = false;
        result.scChatReceiveChat_ = com.randioo.randioo_chat_server.protocol.Chat.SCChatReceiveChat.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.randioo_chat_server.protocol.SCMessage)
    }
    
    static {
      defaultInstance = new SCMessage(true);
      com.randioo.randioo_chat_server.protocol.ServerMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.randioo_chat_server.protocol.SCMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerMessage.proto\022(com.randioo.randi" +
      "oo_chat_server.protocol\032\013Login.proto\032\nPi" +
      "ng.proto\032\nChat.proto\"\313\010\n\tSCMessage\022f\n\031lo" +
      "ginCheckAccountResponse\030\001 \001(\0132C.com.rand" +
      "ioo.randioo_chat_server.protocol.LoginCh" +
      "eckAccountResponse\022b\n\027loginCreateRoleRes" +
      "ponse\030\002 \001(\0132A.com.randioo.randioo_chat_s" +
      "erver.protocol.LoginCreateRoleResponse\022d" +
      "\n\030loginGetRoleDataResponse\030\003 \001(\0132B.com.r" +
      "andioo.randioo_chat_server.protocol.Logi",
      "nGetRoleDataResponse\022L\n\014pingResponse\030\004 \001" +
      "(\01326.com.randioo.randioo_chat_server.pro" +
      "tocol.PingResponse\022f\n\031chatEnterChatRoomR" +
      "esponse\030\005 \001(\0132C.com.randioo.randioo_chat" +
      "_server.protocol.ChatEnterChatRoomRespon" +
      "se\022\\\n\024chatSendChatResponse\030\006 \001(\0132>.com.r" +
      "andioo.randioo_chat_server.protocol.Chat" +
      "SendChatResponse\022d\n\030chatExitChatRoomResp" +
      "onse\030\007 \001(\0132B.com.randioo.randioo_chat_se" +
      "rver.protocol.ChatExitChatRoomResponse\022j",
      "\n\033chatSendPrivateChatResponse\030\010 \001(\0132E.co" +
      "m.randioo.randioo_chat_server.protocol.C" +
      "hatSendPrivateChatResponse\022j\n\033chatShowAc" +
      "countChatResponse\030\t \001(\0132E.com.randioo.ra" +
      "ndioo_chat_server.protocol.ChatShowAccou" +
      "ntChatResponse\022b\n\027chatShowSummaryRespons" +
      "e\030\n \001(\0132A.com.randioo.randioo_chat_serve" +
      "r.protocol.ChatShowSummaryResponse\022V\n\021sc" +
      "ChatReceiveChat\030\013 \001(\0132;.com.randioo.rand" +
      "ioo_chat_server.protocol.SCChatReceiveCh",
      "at"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_randioo_chat_server_protocol_SCMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountResponse", "LoginCreateRoleResponse", "LoginGetRoleDataResponse", "PingResponse", "ChatEnterChatRoomResponse", "ChatSendChatResponse", "ChatExitChatRoomResponse", "ChatSendPrivateChatResponse", "ChatShowAccountChatResponse", "ChatShowSummaryResponse", "ScChatReceiveChat", },
              com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.class,
              com.randioo.randioo_chat_server.protocol.ServerMessage.SCMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.randioo_chat_server.protocol.Login.getDescriptor(),
          com.randioo.randioo_chat_server.protocol.Ping.getDescriptor(),
          com.randioo.randioo_chat_server.protocol.Chat.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
